Repository SpeiserK/TeamExercise, pull requests merged in 2022-09, with the labels that each got.

#3 Adding feature4 to main
  .DS_Store
  scripts/.DS_Store
  scripts/Account.java
  scripts/bankMain.java
Labels: Tasks

#5 Menu Added
  .gitignore
  scripts/bankMain.java
Labels: Tasks

#8 Added create account method. Added actions loop.
  .DS_Store
  scripts/bankMain.java
Labels: Chore, Task

#12 Feature3
  .classpath
  .gitignore
  .project
  scripts/BankAccounts.txt
  scripts/bankMain.java
Labels: Task

#19 add create account test
  scripts/createAccountTest.java
Labels: Task

#20 add comments to create account test
  scripts/createAccountTest.java
Labels: Chore

#21 small fixes and comments
  scripts/Account.java
  scripts/createAccountTest.java
Labels: Chore

#22 fix account creation test
  scripts/createAccountTest.java
Labels: Chore

#23 account creation test formatting
  scripts/createAccountTest.java
Labels: Chore

#24 Deposit and withdraw tests added.
  scripts/depositTest.java
  scripts/withdrawTest.java
Labels: Chore
